### PR TITLE
Add callback to notifications

### PR DESCRIPTION
**Pull request by vrialland**

### CODE REVIEW

**Comment by Oxicode** [comment]
:+1:

**Comment by yerfinojul** [comment]
Can we merge this into pull request?
Thanks!

**Comment by andres-torres-marroquin** [comment]
Looks good to me!

**Comment by GFoley83** [comment]
:+1: Can we get this merged?

**Comment by yerfinojul** [comment]
+1

**Comment by ForNeVeR** [comment]
+1

**Comment by bratva** [comment]
+1

**Comment by GFoley83** [comment]
I removed this library in favour of https://github.com/alexgibson/notify.js
Problem solved.

**Pull request closed without merging**
